### PR TITLE
UI: Header Styling

### PR DESCRIPTION
**Pull request by morkkis**
- The app is now  RTL aligned
- Header styled according to UI styleguides (as close as possible)
- Sidebar is hidden (display: none) vie css

### CODE REVIEW

**Comment by dimkinv** [comment]
@morkkis I see a lot of conflicts with the files. can you check it out?

**Comment by morkkis** [comment]
@dimkinv Guess it's because I've forked from master and trying to merge into branch not so aligned to master. But I can't resolve the conflicts 'cause I don't have write access.

Actually I touched:
src/app/app.component.html
src/app/components/navbar/navbar.component.html
src/app/components/navbar/navbar.component.spec.ts
src/app/components/navbar/navbar.component.ts
src/app/components/sidebar/sidebar.component.html
src/app/components/sidebar/sidebar.component.ts

Ans SCSS file in the 'assets' folder

**Comment by dkhnn** [comment]
Are we looking to merge into master or first merge to portal-pages and then to master?

**Comment by eran1205** [comment]
I started to merge the css styling. I will finish merge it on Sunday with Ivan

**Pull request closed without merging**
